---
layout: pdf
output:
  word_document: default
  html_document:
    df_print: paged
  pdf_document: default
urlcolor: blue
---


Matthew E. Boone  
============================================  
[matt.boone@idfg.idaho.gov](matt.boone@idfg.idaho.gov)   
Data Management Team Lead  
Idaho Department of Fish and Game  
(208) 287-2907

# Education  
**M.S in Wildlife Ecology**, *May 2016* (GPA - 3.90)  
**University of Delaware** *Department of Entomology and Wildlife Ecology*  
Dr. Jeffrey J. Buler  
[*Assessing the effects of Hurricane Sandy on fall migration in the North East United States using Weather Surveillance Radar.* ](http://udspace.udel.edu/handle/19716/19774)  

**B.S in Biology - Ecology, Evolution, and Behavior** *May 2009* (GPA - 3.48)  
**University of Texas**, Austin, TX  

# Experience  

**Data Management Team Lead** *Nov 1, 2020 - Present*  
**Idaho Department of Fish and Game** - Boise, ID  
> - Stuff  
- Things  
- More Stuff  

**Data Mananger and Biologist** *August 9, 2018 - Present*  
**University of Florida Research and Education Center - Ft. Lauderdale**, FL  

> - Manage multitple spatial PostgreSQL databases in lab including database creation, sql query building, and analysis using PostGIS extensions.
- Analyze data sets and create high-quality publication quality maps and graphics using R and QGIS for lab projects.
- Creation, consulting, and managing of multiple software packages in R (detailed below).
- Manage IT workload for multiple computers running Ubuntu and lab server running Debian builds.
- Lead naturalist and logistic support for bi-annual bioblitzes conducted in urban parks across Broward County, Florida. Teach volunteers about collecting data via iNaturalist, lead walks for bioblitz with volunteers, and coordinate email lists and summary reports for the public.
These reports are published online:  
[Tree Tops Park](https://mablab.org/post/2018-11-07-bioblitz-summary/)  
[Quiet Waters Park](https://mablab.org/post/qwp-bioblitz-sumdmary/)
- Trapped over 70 raccoon in a large urban park, administered anesthesia via carefully measured doses, procure blood samples, and apply radio/gps collars to selected individuals. Collect GPS data from the field via a base-station and radio antennae weekly.

**Data Analyst and Database Manager** *April 15, 2016 – April 13, 2017*  
**Kauai Endangered Seabird Recovery Project**, HI  

> -	Analyzed field data and created maps using R and ArcGis. Interfaced with and analyzed data from a myriad of technologies including Audio Recording Units, satellite and geolocator tags, Recoynx Field Cameras, and LiDAR. Fixed, maintained, and expanded two current databases using Microsoft Access and SQL.
-	Prepared 12 annual scientific reports, helped write manuscripts, and lead outreach events for public.
-	Managed nine technicians in office, monitored their data entry, and created projects tailored to each technician's strengths. Helped with field logistics, helicopter flights, and schedules.
-	Created a habitat model for the endangered Band-rumped Storm-Petrel using ten years of auditory survey and Audio Recorded Unit data using boosted regression trees in R
-	Created an algorithm to calculate exposure height of powerline wires across the island of Kauai using LiDAR and Photogrammetry data in R. Required dynamically creating 100,000 geospatial polygons tailored to individual vectors analyzed entirely in an R environment.
-	Analyzed movement and wintering range of 12 satellite tagged juvenile Newell’s Shearwaters using dynamic Brownian Bridge Movement Model in R.
- Monitored seabird colonies in the mountainous regions of Kauai. This included hiking on very steep
terrain in extremely wet conditions. Safely traversed across roped sections on mountain. Performed burrow checks on nesting success of endangered seabirds. Deployed and maintained Automated Recording Units and Reconyx wildlife cameras in the field for monitoring of colonies.

**Woodpecker Crew Leader** *May 1, 2018 – August 9, 2018*  
**Rocky Mountain Research Station - USFS**, ID  

**Avian Crew Leader** *May 1, 2017 – September 30, 2017*  
**National Council for Air and Stream Improvement**, OR  

## Teaching

*2024* **Instructor** 'Going wild with R' **Workshop at Idaho Chapter of the Wildlife Society** (Coeur d'Alene, ID)  
*2023* **Instructor** 'Going wild with R' **Workshop at Idaho Chapter of the Wildlife Society** (Boise, ID)  
*2020* **Instructor** 'Intro to R for Academia' **Workshop for Faculty at Hendrix College** (Conway, AR)  
*2019* **Instructor** 'Data Management with SQL for Ecologists' **Workshop at Tropical REC - UF** (Homested, FL)  
*2019* **Instructor** 'Intro to R for Ecologists' **Workshop at Florida Atlantic University** (Boca Raton, FL)  
*2018* **Instructor** 'Taking the Next Step with R: Data Management, Publication Quality Graphics and Function Building' **Workshop AOS meeting** (Tuscon, AZ)  
*2017* **Instructor** ‘Graphing and Programming in R’ **Workshop at AOSSCO meeting** (East Lansing, MI)    
*2015* **Instructor** 'Taking R to the Next Level' **Workshop at AOU/COS meeting** (Norman, OK)  
*2015* **Guest Lecturer** ‘Programming and Data Processing in R’ (University of Delaware)    
*2014* **Guest Lecturer** Wetland policy and management in the United States **Habitat Management class** (University of Delaware)     

## Volunteer/Service

*2024 - Present* **Treasurer** *Idaho Chapter of The Wildlife Society*  
*2014 - 2021* **eBird Regional Editor** *eBird.org* – Comal and Guadalupe TX counties  
